---
raw_data_path: "M:\\data"
output_path: "M:\\analysis\\Axel_Bisi\\data"
overstrike:
     overstrike_path: "C:\\Users\\bisi\\OverStrike-win"
catgt:
     catgt_path: "C:\\Users\\bisi\\CatGT-win"
kilosort:
     kilosort_path: "C:\\Users\\bisi\\Kilosort\\Kilosort-2.0"
     temp_data_path: "D:\\Npx_Data"
     ks_version: 2.0
     nblocks: 5
     threshold: [ 10, 4 ]
     lambda: 10
     AUC_for_splits: 0.9
tprime:
     tprime_path: "C:\\Users\\bisi\\TPrime-win\\"
     syncperiod: 1,
     default_tostream_probe: 0
cwaves:
     cwaves_path:  "C:\\Users\\bisi\\C_Waves-win"
     samples_per_spike: 82
     pre_samples: 30
     num_spikes: 1000
     snr_radius: 8